[package]
name = "echor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
assert_cmd = "2.0.16"
clap = { version = "4.5.15", features = ["derive"] }
predicates = "3.1.2"
pretty_assertions = "1.4.0"
